replicaCount: 1

port: 3000

canary:
  enabled: false

vpn_ip: 54.93.200.105/32

infisical:
  enabled: true
  host: https://infisical.sre.ideasoft.io/api
  namespace: hackathon-dev
  environment: dev
  tokenSecretName: world-mini-app-infisical-token

normal_deploy:
  enabled: true

version: api-v1

image:
  repository: 335258918943.dkr.ecr.eu-central-1.amazonaws.com/hackaton-world-mini-app
  pullPolicy: Always
  tag: latest
  containerPort: 3000
  livenessProbe:
    path: /
    port: 3000
    periodSeconds: 300
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /
    port: 3000
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: api

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  updated: false
  old: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
