import type { Metadata } from 'next';
import MiniKitProvider from '@/components/minikit-provider';
import dynamic from 'next/dynamic';
import NextAuthProvider from '@/components/next-auth-provider';
import { ThemeProvider } from '@/theme/ThemeProvider';
import { Layout } from '@/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import('../components/Eruda').then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );
  return (
    <html lang="en">
      <NextAuthProvider>
        <ErudaProvider>
          <MiniKitProvider>
            <body>
              <ThemeProvider>
                <Layout>{children}</Layout>
              </ThemeProvider>
            </body>
          </MiniKitProvider>
        </ErudaProvider>
      </NextAuthProvider>
    </html>
  );
}
